/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEmailRenderRouteImport } from './routes/api/public/email/render'

const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailRenderRoute = ApiPublicEmailRenderRouteImport.update({
  id: '/api/public/email/render',
  path: '/api/public/email/render',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/api/public/email/render': typeof ApiPublicEmailRenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/api/public/email/render': typeof ApiPublicEmailRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-preview': typeof EmailPreviewRoute
  '/api/public/email/render': typeof ApiPublicEmailRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email-preview' | '/api/public/email/render'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email-preview' | '/api/public/email/render'
  id: '__root__' | '/' | '/email-preview' | '/api/public/email/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailPreviewRoute: typeof EmailPreviewRoute
  ApiPublicEmailRenderRoute: typeof ApiPublicEmailRenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/render': {
      id: '/api/public/email/render'
      path: '/api/public/email/render'
      fullPath: '/api/public/email/render'
      preLoaderRoute: typeof ApiPublicEmailRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailPreviewRoute: EmailPreviewRoute,
  ApiPublicEmailRenderRoute: ApiPublicEmailRenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
